sudo: required
services:
  - docker

before_install:
  - docker build -t zag2art/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t zag2art/docker-react npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-634376465626"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
